### ISSUE TITLE
Zoom In and Out is inverted 

### ISSUE THREAD

**Issue by AhmedWael205** [BartBrood/Interactive-Graphviz-Diagrams#13]
Zooming In and Out to the graph using the mouse wheel is inverted, I believe the following change can be a possible fix:
@handleZoom() function, Replace:
if (event.deltaY < 0) 
with:
if (event.deltaY >= 0)

Thanks in Advance and Great Work!
Ahmed

**Comment by AhmedWael205** [comment]
And the zooming is always relative to the original graph position, So If I zoomed in to a place and then moved the mouse and tried to zoom in again it doesn't work correctly.

**Comment by BartBrood** [comment]
changed the direction of the zoom, will check the positioning issue later.

**Comment by BartBrood** [comment]
zooming improved, can you verify?

**Comment by AhmedWael205** [comment]
Yes both are now fixed, Thank you :)
